/**
 * Analysis orchestrator.
 *
 * This is the only module the API routes call to get judgement, and it encodes
 * the product's central promise: **the user always gets an answer, and the
 * answer is always labelled with where it came from.**
 *
 * Two paths exist —
 *
 *   live  — a real model answered, its output passed strict validation, and the
 *           UI will say which model produced it.
 *   demo  — the deterministic engine answered, and the UI will say so plainly.
 *
 * There is no third path where machine-generated text is presented as
 * something it is not. Every degradation is accompanied by a `modeReason`
 * explaining in the user's own words why the demo engine answered.
 */

import { toAppError, type ErrorCode } from '../errors';
import { validateAnalysis } from '../schema';
import type { MarketSnapshot, ResearchRequest, ResearchResult } from '../types';
import { buildFallbackAnalysis } from './fallback';
import { buildSystemPrompt, buildUserPrompt } from './prompt';
import { aiKeySource, aiProviderLabel, hasAiKey, requestLiveAnalysis } from './provider';

const DEMO_ENGINE_LABEL = 'Deterministic demo engine';

/**
 * Why the demo engine answered, phrased for a user rather than a developer.
 * Deliberately says nothing about *which* credential is configured or what its
 * value is — only about what the user is looking at.
 */
const DEMO_REASON: Record<ErrorCode, string> = {
  AI_UNAVAILABLE:
    'The analysis engine was unavailable for this request, so this analysis comes from the built-in deterministic engine.',
  AI_RATE_LIMITED:
    'The analysis engine is rate-limiting this deployment right now, so this analysis comes from the built-in deterministic engine. This clears within seconds — the market snapshot is unaffected.',
  AI_BAD_RESPONSE:
    'The analysis engine returned an unusable response, so this analysis comes from the built-in deterministic engine.',
  TIMEOUT:
    'The analysis engine took too long to respond, so this analysis comes from the built-in deterministic engine.',
  NETWORK:
    'The analysis engine could not be reached, so this analysis comes from the built-in deterministic engine.',
  MISSING_MARKET_KEY:
    'The analysis engine is not fully configured on this deployment, so this analysis comes from the built-in deterministic engine.',
  INVALID_TICKER: '',
  UNSUPPORTED_TICKER: '',
  MARKET_UNAVAILABLE: '',
  MARKET_KEY_REJECTED: '',
  MARKET_RATE_LIMITED: '',
  MARKET_BAD_RESPONSE: '',
  BAD_REQUEST: '',
  UNKNOWN: '',
};

function demoResult(
  request: ResearchRequest,
  snapshot: MarketSnapshot,
  reason: string,
): ResearchResult {
  return {
    request,
    snapshot,
    analysis: buildFallbackAnalysis(request, snapshot),
    mode: 'demo',
    providerLabel: DEMO_ENGINE_LABEL,
    modeReason: reason,
  };
}

function reasonFor(code: ErrorCode): string {
  return (
    DEMO_REASON[code] ||
    'The analysis engine could not complete this request, so this analysis comes from the built-in deterministic engine.'
  );
}

/**
 * Produce the full research result for one instrument.
 *
 * Never throws for an AI-layer failure — the whole point is that a judge with
 * no configured key, or a deployment hitting a provider outage, still sees a
 * complete research card. Market-data failures are different and *do* throw,
 * because without a price there is nothing honest to analyse.
 */
export async function runAnalysis(
  request: ResearchRequest,
  snapshot: MarketSnapshot,
): Promise<ResearchResult> {
  if (!hasAiKey()) {
    return demoResult(
      request,
      snapshot,
      'No AI credential is configured on this deployment, so this analysis comes from the built-in deterministic engine rather than a language model.',
    );
  }

  // Recorded before the call so a failure can be attributed without re-reading
  // the environment. This is an env var *name*, never a value.
  const keySource = aiKeySource();

  try {
    const raw = await requestLiveAnalysis(
      buildSystemPrompt(),
      buildUserPrompt(request, snapshot),
    );

    const result = validateAnalysis(raw, request.ticker, {
      // The same field the prompt reads and the UI renders. When a data plan
      // ever supplies a real extended-hours print, the labelling rule lifts
      // everywhere at once rather than in three places independently.
      afterHoursAvailable: snapshot.quote.afterHoursAvailable,
    });

    if (result.ok) {
      const label = aiProviderLabel();
      return {
        request,
        snapshot,
        analysis: result.value,
        mode: 'live',
        providerLabel: label,
        modeReason: `Generated by ${label} from the market snapshot above. Every market number shown comes from the data layer, not from the model.`,
      };
    }

    // Server-side only: the specific rule that failed is developer information.
    console.error('[afterhours] live analysis failed validation', {
      ticker: request.ticker,
      errors: result.errors,
    });
    return demoResult(request, snapshot, reasonFor('AI_BAD_RESPONSE'));
  } catch (err) {
    const appError = toAppError(err, 'AI_UNAVAILABLE');
    console.error('[afterhours] live analysis failed', {
      ticker: request.ticker,
      keySource,
      code: appError.code,
      detail: appError.detail,
    });
    return demoResult(request, snapshot, reasonFor(appError.code));
  }
}
